name: release
on:
  push:
    branches: [main]

jobs:
  release-macos:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
      - name: Configure
        run: cmake -S build-sys -B build-sys/build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build-sys/build
      - name: Install
        run: cmake --install build-sys/build --prefix build-sys/dist
      - name: Verify codesign
        run: codesign --verify --deep --strict build-sys/dist/kehindes_gameboycolor_emulator.app
      - name: Package
        run: cpack --config build-sys/build/CPackConfig.cmake -B build-sys/build/package
      - name: Bump version
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag || steps.bump_version.outputs.previous_tag }}
          files: build-sys/build/package/*.dmg